server.port: 8082


spring:
    jpa:
        show-sql: true
        hibernate.ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL8Dialect
        generate-ddl: true
    datasource:
        url: jdbc:mysql://localhost:3306/paycheck_calculation
        username: paycheck-admin
        password: admin
